- name: Alterar senha de usu치rio em v치rios servidores
  hosts: all
  become: yes

  vars_prompt:
    - name: "username"
      prompt: "Digite o nome de usu치rio: "
      private: no

    - name: "new_password"
      prompt: "Digite a nova senha: "
      private: yes

  tasks:
    - name: Alterar a senha do usu치rio
      user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512') }}"
    - name: Resultado
      debug:
        var: script_output.stdout_lines